services:
  - type: web
    name: THALAPATHY-FILTER-BOT
    env: python
    pythonVersion: 3.10.8
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 bot.py
    branch: main
    plan: free
    region: oregon
    healthCheckPath: /

