services:
  - type: web
    name: THALAPATHY-FILTER-BOT
    env: python
    pythonVersion: 3.10.8        # ‚≠ê REQUIRED to avoid build errors
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/1238muj/THALAPATHY-FILTER-BOT.git
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /

